name: Check

on:
  pull_request:
    branches:
      - main

jobs:
  check:
    name: check on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup tox environment
        run: |
          pip install tox
      - name: Run tox
        run: |
          tox -e check
